[build]
    command = "cd ../../ && pnpm install && pnpm run build && pnpm run build --filter locale-router-static"
    publish = "build"

[[redirects]]
  from = "/*"
  to = "/cs/:splat"
  status = 302
  conditions = {Language = ["cs"]}

[[redirects]]
  from = "/*"
  to = "/de/:splat"
  status = 302
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302