[build]
    command = "cd ../../ && pnpm install && pnpm run build && pnpm --filter locale-router-static run build"
    publish = "build"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/cs/:splat"
  status = 302
  conditions = {Language = ["cs"]}

[[redirects]]
  from = "/*"
  to = "/de/:splat"
  status = 302
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302