[build]
    command = "cd ../../ && pnpm install && pnpm run build && pnpm --filter locale-router-advanced run build"
    publish = "build"

[build.environment]
  NODE_VERSION = "22"

[functions]
  node_bundler = "esbuild"